### PR TITLE
Update comments WRT Qt ≥ 5.9

### PR DESCRIPTION
**Pull request by Olf0**

### CODE REVIEW

**Comment by nephros** [comment]
Actually I think I merged this too quickly - it does not really fit the purpose of the feature branch (which is to deal with https://github.com/storeman-developers/harbour-storeman/issues/301).

I have cherry-picked these and pushed to a new branch https://github.com/nephros/harbour-storeman/tree/todo-qt and will rebase, drop and forcepush the rename-service branch.

If we decide to actually release the sailjail stuff, these can be merged in as well.

**Comment by Olf0** [comment]
> Actually I think I merged this too quickly - it does not really fit the purpose of the feature branch (which is to deal with [storeman-developers#301](https://github.com/storeman-developers/harbour-storeman/issues/301)).

True.

> I have cherry-picked these and pushed to a new branch https://github.com/nephros/harbour-storeman/tree/todo-qt and will rebase, drop and forcepush the rename-service branch.

Fine.
 
> If we decide to actually release the sailjail stuff, these can be merged in as well.

No, I would like to merge them now, as they resolve two of the many points listed at https://github.com/storeman-developers/harbour-storeman/issues/356

But, before I also merge this too quickly: Do you see any reason not to merge https://github.com/storeman-developers/harbour-storeman/pull/357 now?

**Comment by nephros** [comment]
> No, I would like to merge them now, as they resolve two of the many points listed at [storeman-developers#356](https://github.com/storeman-developers/harbour-storeman/issues/356)
> 
> But, before I also merge this too quickly: Do you see any reason not to merge [storeman-developers#357](https://github.com/storeman-developers/harbour-storeman/pull/357) now?

Not really, no.

**Comment by Olf0** [comment]
Done.

**Pull request merged**
